#!/usr/bin/env python

# standard library
import os

def build(bld):

    # Distribute options.
    speed = bld.options.speed
    
    os.chdir(bld.env.project_paths['STRUCT_TOOLBOX'] + '/tests')
    
    bld.add_group()
    
    bld(features = 'run_py_script', source = 'testA.py', target = "",  version = 2)
    
    if(speed):
    
        bld.add_group()
    
        bld(features = 'run_py_script', source = 'testB.py', target = "",  version = 2)
    
    bld.add_group()
    
    bld(features = 'run_py_script', source = 'testC.py', target = "",  version = 2)
    
    bld.add_group()
    
    bld(features = 'run_py_script', source = 'testD.py', target = "",  version = 2)
    
    bld.add_group()
    
    bld(features = 'run_py_script', source = 'testE.py', target = "",  version = 2)
    
    bld.add_group()
    
    #bld(features = 'run_py_script', source = 'testF.py', target = "",  version = 2)
